language: node_js
node_js:
  - 14

services:
  - docker  

stages:
  - build
  - test
  - name: deploy
    if: branch =~ /^feature\/.*$/

# Skip npm install before each stage
install: true

jobs:
  include:
    # BUILD
    - stage: build
      script:
        - npm i 
        - npm run build
      workspaces:
        # Upload node_modules and dist folder
        create:
          name: dependencies
          paths: 
            - node_modules
            - dist

    # TEST
    - stage: test
      workspaces:
        # Donwload dependencies
        use: dependencies
      script: npm run test

    # DEPLOY
    - stage: deploy
      workspaces:
        # Donwload dependencies
        use: dependencies
      script: 
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - aws ecr get-login-password --region $REGION_NAME
        - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PSW
        - docker build -t pchmn/la-danze-en-ldc-twitter-bot . 
        - docker push pchmn/la-danze-en-ldc-twitter-bot:latest
        - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --region $REGION_NAME